chore(build): docker multi-arch images
dadoonet/fscrawler pull request #1518
Opened 2022-10-06 18:15 UTC by 24601

add buildx config for linux/amd64 and linux/arm64 image build and push

2022-10-07 03:30 UTC, dadoonet requested changes
Thanks a lot for this.

Is there anything the end user has to do when he wants to pull the right image or is it done automatically by Docker based on the processor where Docker is running? (N00b question ;) )

2022-10-07 03:30 UTC, dadoonet commented on distribution/pom.xml
> +    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
Could you revert this change?

2022-10-07 03:30 UTC, dadoonet commented on distribution/pom.xml
> +
Could you revert this change?

2022-10-07 04:43 UTC, 24601 commented on distribution/pom.xml
> +    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
Of course. Done!

2022-10-07 04:43 UTC, 24601 commented on distribution/pom.xml
> +
Of course. Done!

2022-10-07 04:45 UTC, 24601 commented
> Thanks a lot for this.
> 
> Is there anything the end user has to do when he wants to pull the right image or is it done automatically by Docker based on the processor where Docker is running? (N00b question ;) )

No, the container runtime (and for sure Docker, but also podman, etc) tend to abstract this away from the user and require no special intervention for selecting platform images in most cases. The cases I have seen this does not happen are mostly edge cases in complicated/hybrid systems and architectures that are definitely edge cases.

2022-11-02 11:07 UTC, dadoonet commented
Hey @24601 

Could you rebase your branch on master?

2023-07-27 09:27 UTC, Logicer16 commented
@24601 Would you mild quickly rebasing this so it can be merged

2023-10-17 09:59 UTC, dadoonet commented
Changes made in #1729

2023-10-17 09:59 UTC, closed without merging